createHeader = function() {
	document.writeln('<div id="vmuTop">');
	document.writeln('	<div class="headerWrap">');
	document.writeln('		<h1 id="vmuLogo">Virgin Mobile</h1>');
	document.writeln('		<div class="navWrap">');
	document.writeln('			<div class="navTop">');
	document.writeln('				<ul class="navTopLeft">');
	document.writeln('					<li><a href="/check-cell-phone-coverage">Coverage Map</a></li><li><a href="http://stores.virginmobileusa.com/cgi-bin/search.pl">Find a Store</a></li><li><a href="http://espanol.virginmobileusa.com/">Espanol</a></li>');
	document.writeln('				</ul>');
	document.writeln('				<ul class="navTopRight">');
	document.writeln('					<li><a href="https://www1.virginmobileusa.com/orderLookupLogin.do">Track Order</a></li><li><a href="https://www1.virginmobileusa.com/activate/activate.do?page=0">Activate</a></li><li><a href="https://www1.virginmobileusa.com/myaccount/topup.do">Top-Up</a></li><li><a href="https://www1.virginmobileusa.com/myaccount/home.do">Manage My Account</a></li>');
	document.writeln('				</ul>');
	document.writeln('			</div>');
	document.writeln('			<div class="navBot">');
	document.writeln('				<ul class="mainNav">');
	document.writeln('					<li><a href="shop.html" id="navShop">SHOP</a></li><li><a href="plans.html" id="navPlans">PLANS</a></li><li><a href="/why-choose-us/" id="navWhy">WHY CHOOSE US</a></li><li><a href="/help-support/" id="navSupport">SUPPORT</a></li><li><a href="https://www1.virginmobileusa.com/order/prepareShoppingcart.do" id="navCart">CART <sup>(10)</sup></a></li>');
	document.writeln('				</ul>');
	document.writeln('			</div>');
	document.writeln('		</div>');
	document.writeln('	</div>');
	document.writeln('	<div class="navShadow"></div>');
	document.writeln('	<div id="megaMenu">');
	document.writeln('		<div id="shopMenu">');
	document.writeln('			<ul id="shopMenuSubNav">');
	document.writeln('				<li><a href="#">SHOP ALL PHONES</a></li>');
	document.writeln('				<li><a href="#">ANDROIDS</a></li>');
	document.writeln('				<li><a href="#">AEROS</a></li>');
	document.writeln('				<li><a href="#">BROADBAND2GO</a></li>');
	document.writeln('				<li><a href="#">ACCESSORIES</a></li>');
	document.writeln('				<li><a href="#">DEALS</a></li>');
	document.writeln('			</ul>');
	document.writeln('			<div class="right">');
	document.writeln('				<div class="promo1"><a href="#">');
	document.writeln('					<h2>BEYOND TALK UNLIMITED DATA PHONES</h2>');
	document.writeln('					<p>// SHOP NOW</p>');
	document.writeln('				</a></div>');
	document.writeln('				<div class="promo2"><a href="#">');
	document.writeln('					<h2>payLo Talk &amp; Text Plans</h2>');
	document.writeln('					<p>// SHOP NOW</p>');
	document.writeln('				</a></div>');
	document.writeln('				');
	document.writeln('			</div>');
	document.writeln('		</div>');
	document.writeln('		<div id="plansMenu">');
	document.writeln('			<div class="left">');
	document.writeln('				<h1><a href="#">ALL OUR PLANS</a> ARE NO CONTRACT</h1>');
	document.writeln('				<div class="promo1"><a href="#">');
	document.writeln('					<h2>BEYOND TALK UNLIMITED DATA PLANS</h2>');
	document.writeln('					<p>Unlimited Web, Data, Messaging, &amp; Email. Plus, hundreds of anytime minutes.</p>');
	document.writeln('					<p>// STARTING AT $35/MONTH</p>');
	document.writeln('				</a></div>');
	document.writeln('			</div>');
	document.writeln('			<div class="right">');
	document.writeln('				<h2><a href="#">// INTERNATIONAL RATES</a></h2>');
	document.writeln('				<div class="promo2"><a href="#">');
	document.writeln('					<h2>BROADBAND2GO MOBILE WI-FI PLANS</h2>');
	document.writeln('					<p>3G Internet at Home or On The Go.</p>');
	document.writeln('				</a></div>');
	document.writeln('				<div class="promo3"><a href="#">');
	document.writeln('					<h2>payLo Talk &amp; Text Plans</h2>');
	document.writeln('					<p>Say more, don’t pay more. Talk and Text.</p>');
	document.writeln('				</a></div>');
	document.writeln('			</div>');
	document.writeln('		</div>');
	document.writeln('	</div>');
	document.writeln('</div>');
}



createFooter = function() {

	document.writeln('<div id="vmuBot">');
	document.writeln('	<div class="footerWrap">');
	document.writeln('		');
	document.writeln('		<div class="footerBlock" id="shopLinks">');
	document.writeln('			<div class="header"><h1>SHOP</h1></div>');
	document.writeln('			<ul>');
	document.writeln('				<li><a href="#">Shop All Phones</a></li>');
	document.writeln('				<li><a href="#">Android Phones</a></li>');
	document.writeln('				<li><a href="#">Smartphones</a></li>');
	document.writeln('				<li><a href="#">Feature Phones</a></li>');
	document.writeln('				<li><a href="#">Broadband Devices</a></li>');
	document.writeln('				<li><a href="/cell-phone-accessories/">Accessories</a></li>');
	document.writeln('				<li><a href="/deals.html">Deals</a></li>');
	document.writeln('			</ul>');
	document.writeln('		</div>');
	document.writeln('		');
	document.writeln('		<div class="footerBlock" id="plansLinks">');
	document.writeln('			<div class="header"><h1>PLANS</h1></div>');
	document.writeln('			<ul>');
	document.writeln('				<li><a href="/cell-phone-plans/beyond-talk-plans.jsp">Beyond Talk Unlimited Data Plans</a></li>');
	document.writeln('				<li><a href="/cell-phone-plans/paylo-plans.jsp">PayLo Talk &amp; Text Plans</a></li>');
	document.writeln('				<li><a href="/mobile-broadband/broadband2go.html">Broadband Plans</a></li>');
	document.writeln('			</ul>');
	document.writeln('		</div>');
	document.writeln('		');
	document.writeln('		<div class="footerBlock" id="usefulLinks">');
	document.writeln('			<div class="header"><h1>SOME USEFUL LINKS</h1></div>');
	document.writeln('			<div class="left">');
	document.writeln('				<ul>');
	document.writeln('					<li><a href="#">Us Vs. Them</a></li>');
	document.writeln('					<li><a href="/help-support/">Support</a></li>');
	document.writeln('					<li><a href="/about-virgin-mobile">About us</a></li>');
	document.writeln('					<li><a href="/about-virgin-mobile/virgin-mobile-careers-jobs">Careers</a></li>');
	document.writeln('					<li><a href="/sitemap">Sitemap</a></li>');
	document.writeln('					<li><a href="/check-cell-phone-coverage">Coverage Map</a></li>');
	document.writeln('					<li><a href="https://ringbacktones.virginmobileusa.com/vmuweb/web/welcome.do">Ringbacks</a></li>');
	document.writeln('				</ul>');
	document.writeln('			</div>');
	document.writeln('			<div class="right">');
	document.writeln('				<ul>');
	document.writeln('					<li><a href="http://newsroom.virginmobileusa.com/">Media Room</a></li>');
	document.writeln('					<li><a href="http://www.youtube.com/virginmobileusa">Commercials</a></li>');
	document.writeln('					<li><a href="/about/affiliate-program.html">Affiliates</a></li>');
	document.writeln('					<li><a href="http://virginmobileusa.marketwire.com/easyir/home.do?easyirid=F4ABAEBA3A27ECD9">Corporate Relations</a></li>');
	document.writeln('					<li><a href="http://stores.virginmobileusa.com/cgi-bin/search.pl">Find A Store</a></li>');
	document.writeln('				</ul>');
	document.writeln('			</div>');
	document.writeln('		</div>');
	document.writeln('		');
	document.writeln('		');
	document.writeln('		<div class="footerBlock" id="connectLinks">');
	document.writeln('			<div class="header"><h1>CONNECT WITH US</h1></div>');
	document.writeln('			<ul class="social">');
	document.writeln('				<li><a href="http://www.youtube.com/virginmobileusa" class="youtube">YouTube</a></li>');
	document.writeln('				<li><a href="https://www.facebook.com/VirginMobileUSA" class="facebook">Facebook</a></li>');
	document.writeln('				<li><a href="http://www.flickr.com/photos/37089719@N08/" class="flickr">Flickr</a></li>');
	document.writeln('				<li><a href="https://twitter.com/#!/virginmobileus" class="twitter">Twitter</a></li>');
	document.writeln('				<li><a href="http://www.tumblr.com/tagged/virgin-mobile" class="tumblr">Tumblr</a></li>');
	document.writeln('				<li><a href="http://pinterest.com/virginmlive/" class="pinterest">Pintrest</a></li>');
	document.writeln('				<li><a href="https://www.facebook.com/VirginMobileLive?cmpid=p-footer-100411" class="virginlive">Live</a></li>');
	document.writeln('			</ul>');
	document.writeln('			<div class="quote">');
	document.writeln('				<p>&ldquo;AMAZING!!! I wanted an android phone and Virgin ');
	document.writeln('				Mobile gave it to me at a lower price with a lower ');
	document.writeln('				monthly bill than I could have gotten anywhere else.&rdquo;</p>');
	document.writeln('				<p class="credit">&ndash; Sasha F. <span>(Oklahaoma City, OK)</span></p>');
	document.writeln('			</div>');
	document.writeln('			');
	document.writeln('		</div>');
	document.writeln('		');
	document.writeln('		');
	document.writeln('		');
	document.writeln('		<div id="copyLine">');
	document.writeln('			<div class="left">&copy;2002 - 2012 Virgin Mobile USA USA, L.P. All Rights Reserved</div>');
	document.writeln('			<div class="right">');
	document.writeln('				<ul>');
	document.writeln('					<li><a href="/legal/privacy-policy">Privacy Policy</a></li>');
	document.writeln('					<li><a href="/legal/copyright-info">Copyright Notice</a></li>');
	document.writeln('					<li><a href="/legal/terms-of-website-use">Web Site &amp; Use Terms</a></li>');
	document.writeln('					<li><a href="/legal/adchoices.html">AdChoices</a></li>');
	document.writeln('					<li><a href="/networkmanagement">Net Neutrality</a></li>');
	document.writeln('					<li><a href="/about/ctia.html">CITIA Consumer Checklist</a></li>');
	document.writeln('				</ul>');
	document.writeln('			</div>');
	document.writeln('		</div>');
	document.writeln('		');
	document.writeln('	</div>');
	document.writeln('</div>');
};

